trigger:
  - main

# 👇 Target your self-hosted agent in Default pool
pool:
  name: 'Default'
  demands:
    - Agent.Name -equals SeftHosted

variables:
  dockerRegistryServiceConnection: 'ilifes-acr-docker'   # ✅ use your working service connection
  imageName: 'buildprocure-apache'                       # repository name inside ACR
  acrName: 'ilifesregistry.azurecr.io'
  imageTag: 'latest'

stages:
  - stage: Build
    displayName: 'Build and Push Apache Image'
    jobs:
      - job: Build
        displayName: 'Build Apache'
        pool:
          name: 'Default'
          demands:
            - Agent.Name -equals SeftHosted 

        steps:
          - checkout: self

          # Debug: List repo contents
          - script: |
              echo "Listing repo files..."
              dir
            displayName: 'Debug: Show checked out files'
            shell: cmd

          - task: Docker@2
            displayName: 'Docker Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Build Apache Image'
            inputs:
              command: build
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              dockerfile: Dockerfile
              tags: |
                $(imageTag)
                $(Build.BuildId)
              buildContext: .

          - task: Docker@2
            displayName: 'Push Apache Image'
            inputs:
              command: push
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageName)
              tags: |
                $(imageTag)
                $(Build.BuildId)
